Stream benchmark data to fix OOM (#6471)
The server was buffering the entire gzipped benchmark dataset into
memory via Buffer.from(await res.arrayBuffer()) before processing it. As
the data grew (especially after #6371 added more random access
  benchmarks), this exceeded the V8 heap limit.
  
```
  <--- Last few GCs --->

[1:0xffff880f0000]   377452 ms: Scavenge (interleaved) 1894.4 (1907.5) -> 1887.5 (1907.7) MB, pooled: 0 MB, 42.69 / 0.00 ms  (average mu = 0.309, current mu = 0.272) allocation failure;
[1:0xffff880f0000]   379461 ms: Mark-Compact (reduce) 1900.3 (1913.2) -> 1885.7 (1892.7) MB, pooled: 0 MB, 1354.23 / 0.00 ms  (+ 417.8 ms in 203 steps since start of marking, biggest step 40.1 ms, walltime since start of marking 2001 ms) (average mu = 0.2
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----
```

Based on the stack trace, the heap seems to be 2G. To reproduce the oom,
one can run ` node --max-old-space-size=512 server.js`. This fails on
develop but doesn't on this branch.

Signed-off-by: Baris Palaska <barispalaska@gmail.com>